Terraform 1
Otus-DevOps-2020-05/nluzgin_infra pull request #5
Opened 2020-07-09 19:07 UTC by nluzgin

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Установлен terraform
- Изучены основные команды terraform
- Сконфигурированы файлы для terraform, позволяющие создать compute engine в GC
- С помощью terraform развёрнуто приложение reddit

Задание с *

- Добавьте в веб интерфейсе ssh ключ пользователю appuser_web в метаданные проекта. Выполните terraform apply и проверьте результат Какие проблемы вы обнаружили? 

После применения конфигурации terraform ssh ключи перезатираются.

Задание с **

Балансер с ip forwarding:

1) создание HTTP балансировщика

resource "google_compute_target_pool" "reddit-app-pool" 
+
resource "google_compute_http_health_check" "reddit-app-pool_hc"
+
resource "google_compute_forwarding_rule" "reddit-app-forwarding"

Вывод в лог value = google_compute_forwarding_rule.reddit-app-forwarding.ip_address

2) 2 приложения с помощью count
Имя "${var.app_name}-${count.index}"
+ count = var.count_of_applications

## Как запустить проект:
 - 

## Как проверить работоспособность:
 - http://35.233.30.173:9292/ -  само приложение 
- http://104.199.69.179:9292/  -  балансер

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2020-07-10 06:17 UTC, mrgreyves requested changes
Здравствуйте!) К сожалению тесты красные, вам стоит изменить версию терраформ, в используемой версии некоторые конструкции не поддерживаются.

2020-07-10 07:46 UTC, nluzgin commented
> Здравствуйте!) К сожалению тесты красные, вам стоит изменить версию терраформ, в используемой версии некоторые конструкции не поддерживаются.

А почему нудна конкретная версия? в доках другая....

2020-07-10 07:53 UTC, nluzgin commented
> > Здравствуйте!) К сожалению тесты красные, вам стоит изменить версию терраформ, в используемой версии некоторые конструкции не поддерживаются.
> 
> А почему нудна конкретная версия? в доках другая....

Причём нужна именно 0.12.19, хотя в доках 0.12.8, а последняя 0.12.29...

2020-07-11 09:42 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все выполнено корректно. Идея в не очень точном указании какую версию терраформа использовать заключается в том, что для тестов могут использоваться образы с терраформом отличным от вашего =)

2020-07-11 10:48 UTC, merged